version: '3.7'

services:
  # Service 1: Forms Flow Documents
  forms-flow-documents-api:
    container_name: forms-flow-documents-local
    build:
      context: ./forms-flow-ai/forms-flow-ai-ee/forms-flow-documents
      dockerfile: local.Dockerfile
      args:
        - ssh_prv_key=${SSH_PRV_KEY}
        - ssh_pub_key=${SSH_PUB_KEY}
    restart: unless-stopped
    ports:
      - '5006:5006'
    volumes:
      - ./forms-flow-ai/forms-flow-ai-ee/forms-flow-documents:/app:rw
      - ./forms-flow-ai/forms-flow-ai-ee/forms-flow-documents/src:/local_src:ro
    entrypoint: /local_entrypoint.sh
    environment:
      DATABASE_URL: ${FORMSFLOW_API_DB_URL:-postgresql://postgres:changeme@forms-flow-webapi-db:5432/webapi}
      FORMSFLOW_API_CORS_ORIGINS: ${FORMSFLOW_API_CORS_ORIGINS:-*}
      JWT_OIDC_WELL_KNOWN_CONFIG: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}/.well-known/openid-configuration
      JWT_OIDC_JWKS_URI: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}/protocol/openid-connect/certs
      JWT_OIDC_ISSUER: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}
      JWT_OIDC_AUDIENCE: ${KEYCLOAK_WEB_CLIENT_ID:-forms-flow-web}
      JWT_OIDC_CACHING_ENABLED: 'True'
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_URL_REALM: ${KEYCLOAK_URL_REALM:-forms-flow-ai}
      FORMSFLOW_API_URL: ${FORMSFLOW_API_URL}
      FORMSFLOW_DOC_API_URL: ${FORMSFLOW_DOC_API_URL}
      FORMIO_URL: ${FORMIO_DEFAULT_PROJECT_URL}
      FORMIO_ROOT_EMAIL: ${FORMIO_ROOT_EMAIL:-admin@example.com}
      FORMIO_ROOT_PASSWORD: ${FORMIO_ROOT_PASSWORD:-changeme}
      CHROME_DRIVER_PATH: ${CHROME_DRIVER_PATH}
      CUSTOM_SUBMISSION_URL: ${CUSTOM_SUBMISSION_URL}
      CUSTOM_SUBMISSION_ENABLED: ${CUSTOM_SUBMISSION_ENABLED}
      FORMIO_JWT_SECRET: ${FORMIO_JWT_SECRET:---- change me now ---}
      MULTI_TENANCY_ENABLED: ${MULTI_TENANCY_ENABLED:-false}
      KEYCLOAK_ENABLE_CLIENT_AUTH: ${KEYCLOAK_ENABLE_CLIENT_AUTH:-false}
    stdin_open: true
    tty: true
    networks:
      - forms-flow-webapi-network

  # Service 2: Forms Flow Nav
  forms-flow-nav:
    container_name: forms-flow-nav-local
    build:
      context: ./forms-flow-ai/forms-flow-ai-micro-front-ends/forms-flow-nav
      dockerfile: local.Dockerfile
    ports:
      - "3005:3005"
    volumes:
      - ./forms-flow-ai/forms-flow-ai-micro-front-ends/forms-flow-nav:/local_src:ro
    environment:
      - REACT_APP_CUSTOM_LOGOUT_URL=${EPD_IDP_LOGOUT_URL}
    tty: true
    networks:
      - forms-flow-webapi-network

  # Service 3: Forms Flow Theme
  forms-flow-theme:
    container_name: forms-flow-theme-local
    build:
      context: ./forms-flow-ai/forms-flow-ai-micro-front-ends/forms-flow-theme
      dockerfile: local.Dockerfile
    ports:
      - "3008:3008"
    volumes:
      - ./forms-flow-ai/forms-flow-ai-micro-front-ends/forms-flow-theme:/local_src:ro
    tty: true
    networks:
      - forms-flow-webapi-network

networks:
  forms-flow-webapi-network:
    driver: 'bridge'

volumes:
  mdb-data:
