version: '3.7'

services:
  # Service 1: Forms Flow Documents
  forms-flow-documents-api:
    container_name: forms-flow-documents-local
    build:
      context: ./forms-flow-ai/forms-flow-ai-ee/forms-flow-documents
      dockerfile: local.Dockerfile
      args:
        - ssh_prv_key=${SSH_PRV_KEY}
        - ssh_pub_key=${SSH_PUB_KEY}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '5006:5006'
    volumes:
      - ./forms-flow-ai/forms-flow-ai-ee/forms-flow-documents:/app:rw
      - ./forms-flow-ai/forms-flow-ai-ee/forms-flow-documents/src:/local_src:ro
    entrypoint: /local_entrypoint.sh
    environment:
      DATABASE_URL: ${FORMSFLOW_API_DB_URL:-postgresql://postgres:changeme@forms-flow-webapi-db:5432/webapi}
      FORMSFLOW_API_CORS_ORIGINS: ${FORMSFLOW_API_CORS_ORIGINS:-*}
      JWT_OIDC_WELL_KNOWN_CONFIG: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}/.well-known/openid-configuration
      JWT_OIDC_JWKS_URI: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}/protocol/openid-connect/certs
      JWT_OIDC_ISSUER: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}
      JWT_OIDC_AUDIENCE: ${KEYCLOAK_WEB_CLIENT_ID:-forms-flow-web}
      JWT_OIDC_CACHING_ENABLED: 'True'
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_URL_REALM: ${KEYCLOAK_URL_REALM:-forms-flow-ai}
      FORMSFLOW_API_URL: ${FORMSFLOW_API_URL}
      FORMSFLOW_DOC_API_URL: ${FORMSFLOW_DOC_API_URL}
      FORMIO_URL: ${FORMIO_DEFAULT_PROJECT_URL}
      FORMIO_ROOT_EMAIL: ${FORMIO_ROOT_EMAIL:-admin@example.com}
      FORMIO_ROOT_PASSWORD: ${FORMIO_ROOT_PASSWORD:-changeme}
      CHROME_DRIVER_PATH: ${CHROME_DRIVER_PATH}
      CUSTOM_SUBMISSION_URL: ${CUSTOM_SUBMISSION_URL}
      CUSTOM_SUBMISSION_ENABLED: ${CUSTOM_SUBMISSION_ENABLED}
      FORMIO_JWT_SECRET: ${FORMIO_JWT_SECRET:---- change me now ---}
      MULTI_TENANCY_ENABLED: ${MULTI_TENANCY_ENABLED:-false}
      KEYCLOAK_ENABLE_CLIENT_AUTH: ${KEYCLOAK_ENABLE_CLIENT_AUTH:-false}
    stdin_open: true
    tty: true
    networks:
      - forms-flow-webapi-network

  # Service 2: Forms Flow Nav
  forms-flow-nav:
    container_name: forms-flow-nav-local
    build:
      context: ./forms-flow-ai/forms-flow-ai-micro-front-ends/forms-flow-nav
      dockerfile: local.Dockerfile
    ports:
      - "3005:3005"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./forms-flow-ai/forms-flow-ai-micro-front-ends/forms-flow-nav:/local_src:ro
    environment:
      - REACT_APP_CUSTOM_LOGOUT_URL=${EPD_IDP_LOGOUT_URL}
    tty: true
    networks:
      - forms-flow-webapi-network

  # Service 3: Forms Flow Theme
  forms-flow-theme:
    container_name: forms-flow-theme-local
    build:
      context: ./forms-flow-ai/forms-flow-ai-micro-front-ends/forms-flow-theme
      dockerfile: local.Dockerfile
    ports:
      - "3008:3008"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./forms-flow-ai/forms-flow-ai-micro-front-ends/forms-flow-theme:/local_src:ro
    tty: true
    networks:
      - forms-flow-webapi-network

  # Service 4: Forms Flow BPM Database
  forms-flow-bpm-db:
    image: postgres:17
    container_name: forms-flow-bpm-db
    environment:
      POSTGRES_USER: ${CAMUNDA_JDBC_USER:-admin}
      POSTGRES_PASSWORD: ${CAMUNDA_JDBC_PASSWORD:-changeme}
      POSTGRES_DB: ${CAMUNDA_JDBC_DB_NAME:-formsflow-bpm}
    ports:
      - '5432:5432'
    restart: unless-stopped
    networks:
      - forms-flow-webapi-network

  # Service 5: Forms Flow BPM
  forms-flow-bpm:
    container_name: forms-flow-bpm-local
    build:
      context: ./forms-flow-ai/forms-flow-ai-ee/forms-flow-bpm
      dockerfile: Dockerfile
      args:
        - ssh_prv_key=${SSH_PRV_KEY}
        - ssh_pub_key=${SSH_PUB_KEY}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - forms-flow-bpm-db
    ports:
      - '8000:8080'
    environment:
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_URL_REALM=${KEYCLOAK_URL_REALM:-forms-flow-ai}
      - KEYCLOAK_CLIENTID=${KEYCLOAK_BPM_CLIENT_ID:-forms-flow-bpm}
      - KEYCLOAK_CLIENTSECRET=${KEYCLOAK_BPM_CLIENT_SECRET:-e4bdbd25-1467-4f7f-b993-bc4b1944c943}
      - CAMUNDA_JDBC_URL=${CAMUNDA_JDBC_URL:-jdbc:postgresql://forms-flow-bpm-db:5432/formsflow-bpm}
      - CAMUNDA_JDBC_USER=${CAMUNDA_JDBC_USER:-admin}
      - CAMUNDA_JDBC_PASSWORD=${CAMUNDA_JDBC_PASSWORD:-changeme}
      - CAMUNDA_JDBC_DRIVER=${CAMUNDA_JDBC_DRIVER:-org.postgresql.Driver}
      - CAMUNDA_APP_ROOT_LOG_FLAG=${CAMUNDA_APP_ROOT_LOG_FLAG:-error}
      - FORMSFLOW_API_URL=${FORMSFLOW_API_URL}
      - FORMIO_URL=${FORMIO_DEFAULT_PROJECT_URL}
      - FORMIO_ROOT_EMAIL=${FORMIO_ROOT_EMAIL:-admin@example.com}
      - FORMIO_ROOT_PASSWORD=${FORMIO_ROOT_PASSWORD:-changeme}
      - APP_SECURITY_ORIGIN=${APP_SECURITY_ORIGIN:-*}
      - WEBSOCKET_SECURITY_ORIGIN=${WEBSOCKET_SECURITY_ORIGIN}
      - WEBSOCKET_MESSAGE_TYPE=${WEBSOCKET_MESSAGE_TYPE:-TASK_EVENT}
      - WEBSOCKET_ENCRYPT_KEY=${WEBSOCKET_ENCRYPT_KEY:-giert989jkwrgb@DR55}
      - DATA_BUFFER_SIZE=${DATA_BUFFER_SIZE:-2}
      - IDENTITY_PROVIDER_MAX_RESULT_SIZE=${IDENTITY_PROVIDER_MAX_RESULT_SIZE:-250}
      - KEYCLOAK_WEB_CLIENTID=${KEYCLOAK_WEB_CLIENTID:-}
      - KEYCLOAK_ENABLE_CLIENT_AUTH=${KEYCLOAK_ENABLE_CLIENT_AUTH:-false}
      - BPM_CLIENT_CONN_TIMEOUT=${BPM_CLIENT_CONN_TIMEOUT:-5000}
      - DATA_ANALYSIS_URL=${DATA_ANALYSIS_URL}
      - CUSTOM_SUBMISSION_URL=${CUSTOM_SUBMISSION_URL}
      - CUSTOM_SUBMISSION_ENABLED=${CUSTOM_SUBMISSION_ENABLED:-false}
      - MULTI_TENANCY_ENABLED=${MULTI_TENANCY_ENABLED:-false}
      - FORMSFLOW_ADMIN_URL=${FORMSFLOW_ADMIN_URL:-}
      - REDIS_ENABLED=${REDIS_ENABLED:-false}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSCODE=${REDIS_PASSCODE:-changeme}
      - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE:-false}
      - CHES_CLIENT_ID=CDACC9DF-68BE85E6452
      - CHES_SECRET=${CHES_SECRET}
      - CHES_AUTH_URL=https://dev.loginproxy.gov.bc.ca/auth/realms/comsvcauth/protocol/openid-connect/token
      - CHES_HOST_URL=https://ches-dev.api.gov.bc.ca
      - COMS_ENDPOINT=${COMS_ENDPOINT}
      - COMS_BUCKET=${COMS_BUCKET}
      - COMS_ACCESS_KEY_ID=${COMS_ACCESS_KEY_ID}
      - COMS_ACCESS_KEY=${COMS_ACCESS_KEY}
      - BCBOX_AUTH_URL=https://epd-keycloak-dev.apps.silver.devops.gov.bc.ca/auth/realms/forms-flow-ai/protocol/openid-connect/token
      - BCBOX_CLIENT_ID=${BCBOX_CLIENT_ID}
      - BCBOX_SECRET=${BCBOX_SECRET}
      - BCBOX_HOST_URL=https://bcbox-e38158-dev.apps.silver.devops.gov.bc.ca
      - COMS_API_HOST_URL=https://common-object-management-service-coms-custom-e38158-dev.apps.silver.devops.gov.bc.ca
      - EPD_SUPPORT_EMAIL=midhun.murali@aot-technologies.com  
      - APP_HOST=${APP_HOST:-epd-frontend-dev.apps.silver.devops.gov.bc.ca}
    networks:
      - forms-flow-webapi-network

  # Service 6: Forms Flow Web
  forms-flow-web:
    container_name: forms-flow-web-local
    build:
      context: ./forms-flow-ai/forms-flow-ai-ee/forms-flow-web
      dockerfile: local.Dockerfile
      args:
        - ssh_prv_key=${SSH_PRV_KEY}
        - ssh_pub_key=${SSH_PUB_KEY}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3004:3004"
    volumes:
      - ./forms-flow-ai/forms-flow-ai-ee/forms-flow-web:/local_src:ro
    environment:
      - HOST=0.0.0.0
      - PORT=3004
    tty: true
    networks:
      - forms-flow-webapi-network

  # Service 7: Forms Flow Web Root Config
  forms-flow-web-root-config:
    container_name: forms-flow-web-root-config-local
    build:
      context: ./forms-flow-ai/forms-flow-ai-ee/forms-flow-web-root-config
      dockerfile: local.Dockerfile
      args:
        - ssh_prv_key=${SSH_PRV_KEY}
        - ssh_pub_key=${SSH_PUB_KEY}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - forms-flow-web
      - forms-flow-nav
      - forms-flow-theme
    ports:
      - "3000:3000"
    volumes:
      - ./forms-flow-ai/forms-flow-ai-ee/forms-flow-web-root-config:/local_src:ro
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - MF_FORMSFLOW_WEB_URL=${MF_FORMSFLOW_WEB_URL:-http://localhost:3004/forms-flow-web.js}
      - MF_FORMSFLOW_NAV_URL=${MF_FORMSFLOW_NAV_URL:-http://localhost:3005/forms-flow-nav.js}
      - MF_FORMSFLOW_SERVICE_URL=${MF_FORMSFLOW_SERVICE_URL:-https://forms-flow-microfrontends.aot-technologies.com/forms-flow-service@v5.2.1-alpha/forms-flow-service.gz.js}
      - MF_FORMSFLOW_ADMIN_URL=${MF_FORMSFLOW_ADMIN_URL:-https://forms-flow-microfrontends.aot-technologies.com/forms-flow-admin@v5.2.1-alpha/forms-flow-admin.gz.js}
      - MF_FORMSFLOW_THEME_URL=${MF_FORMSFLOW_THEME_URL:-http://localhost:3008/forms-flow-theme.js}
      - REACT_APP_API_SERVER_URL=${FORMIO_DEFAULT_PROJECT_URL:-http://localhost:3001}
      - REACT_APP_API_PROJECT_URL=${FORMIO_DEFAULT_PROJECT_URL:-http://localhost:3001}
      - REACT_APP_KEYCLOAK_CLIENT=${KEYCLOAK_WEB_CLIENT_ID:-forms-flow-web}
      - REACT_APP_WEB_BASE_URL=${FORMSFLOW_API_URL:-http://localhost:5000}
      - REACT_APP_BPM_URL=${BPM_API_URL:-http://localhost:8000/camunda}
      - REACT_APP_WEBSOCKET_ENCRYPT_KEY=${WEBSOCKET_ENCRYPT_KEY:-giert989jkwrgb@DR55}
      - REACT_APP_KEYCLOAK_URL_REALM=${KEYCLOAK_URL_REALM:-forms-flow-ai}
      - REACT_APP_KEYCLOAK_URL=${KEYCLOAK_URL:-}
      - REACT_APP_APPLICATION_NAME=${APPLICATION_NAME:-formsflow.ai}
      - REACT_APP_ENABLE_APPLICATION_ACCESS_PERMISSION_CHECK=${ENABLE_APPLICATION_ACCESS_PERMISSION_CHECK:-false}
      - REACT_APP_WEB_BASE_CUSTOM_URL=${WEB_BASE_CUSTOM_URL:-}
      - REACT_APP_MULTI_TENANCY_ENABLED=${MULTI_TENANCY_ENABLED:-false}
      - REACT_APP_MT_ADMIN_BASE_URL=${MT_ADMIN_BASE_URL:-}
      - REACT_APP_MT_ADMIN_BASE_URL_VERSION=${MT_ADMIN_BASE_URL_VERSION:-}
      - REACT_APP_CUSTOM_SUBMISSION_URL=${CUSTOM_SUBMISSION_URL:-}
      - REACT_APP_CUSTOM_SUBMISSION_ENABLED=${CUSTOM_SUBMISSION_ENABLED:-false}
      - REACT_APP_DRAFT_ENABLED=${DRAFT_ENABLED:-false}
      - REACT_APP_DRAFT_POLLING_RATE=${DRAFT_POLLING_RATE:-15000}
      - REACT_APP_EXPORT_PDF_ENABLED=${EXPORT_PDF_ENABLED:-false}
      - REACT_APP_PUBLIC_WORKFLOW_ENABLED=${PUBLIC_WORKFLOW_ENABLED:-false}
      - REACT_APP_DOCUMENT_SERVICE_URL=${DOCUMENT_SERVICE_URL:-http://localhost:5006}
      - REACT_APP_CUSTOM_THEME_URL=${CUSTOM_THEME_URL:-}
      - REACT_APP_CUSTOM_RESOURCE_BUNDLE_URL=${CUSTOM_RESOURCE_BUNDLE_URL:-}
      - REACT_APP_KEYCLOAK_ENABLE_CLIENT_AUTH=${KEYCLOAK_ENABLE_CLIENT_AUTH:-false}
      - REACT_APP_ENABLE_FORMS_MODULE=${ENABLE_FORMS_MODULE:-true}
      - REACT_APP_ENABLE_TASKS_MODULE=${ENABLE_TASKS_MODULE:-true}
      - REACT_APP_ENABLE_DASHBOARDS_MODULE=${ENABLE_DASHBOARDS_MODULE:-true}
      - REACT_APP_ENABLE_PROCESSES_MODULE=${ENABLE_PROCESSES_MODULE:-true}
      - REACT_APP_ENABLE_APPLICATIONS_MODULE=${ENABLE_APPLICATIONS_MODULE:-true}
      - REACT_APP_CUSTOM_MAP_URL=${EPD_CUSTOM_MAP_URL:-http://localhost:4000/map}
      - REACT_APP_CUSTOM_LOGOUT_URL=${EPD_IDP_LOGOUT_URL:-}
      - REACT_APP_SUPPORT_EMAIL=${EPD_SUPPORT_EMAIL:-support@epp.gov.bc.ca}
      - REACT_APP_CUSTOM_FILE_UPLOAD=${EPD_APP_FILE_UPLOAD:-http://localhost:4000/fileupload}
    tty: true
    networks:
      - forms-flow-webapi-network

networks:
  forms-flow-webapi-network:
    driver: 'bridge'

volumes:
  mdb-data:
