Domain: #<DEFINE_ME>
admin:
  email: "me@defineme.com"
  password: "admin"
formsflow:
  configmap: forms-flow-ai #integration env vars
  secret: forms-flow-ai # integration env vars secret
  auth: forms-flow-ai-auth
image:
  registry: docker.io
  repository: formsflow/forms-flow-forms
  tag: v5.2.0 #The image tag to pull from
  secret: ""
ingress:
  ingressClassName: ""
  annotations:
  #    kubernetes.io/ingress.class: nginx
  enabled: true # create an ingress for this component
  hostname: "{{.Chart.Name}}-{{.Release.Namespace}}.{{tpl .Values.Domain .}}"
  port: 3001
  tls: true
  selfSigned: false
  extraTls:
    - {}
resources:
  limits:
    cpu: 200m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 512Mi
