apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "{{ .Chart.Name }}-{{.Release.Namespace}}"
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: { { .Values.issuer.acmeEmail } }
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: "{{ .Chart.Name }}-{{.Release.Namespace}}"
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: { { .Values.issuer.ingressClass } }
