name: forms-flow-web-root-config Custom

on:
  workflow_dispatch:
    inputs:
      START_BUILD:
        required: true
        type: boolean
        description: This value is ignored, just to trigger dispatch.
  push:
    branches:
      - dev
      - main

    paths:
      - "backend/**"
      - "frontend/**"
      - "forms-flow-ai/**"
      - ".github/workflows/**"

defaults:
  run:
    shell: bash
    working-directory: ./forms-flow-ai/forms-flow-ai-ee/forms-flow-web-root-config
env:
  APP_NAME: "forms-flow-web-root-config"

jobs:
  forms-flow-ai-web-root-config-cd-by-push:
    runs-on: ubuntu-20.04

    if: github.repository == 'bcgov/nr-epd-digital-services'
    steps:
      - uses: actions/checkout@v2
      - name: Set ENV variables
        id: set-variable
        # make sure to update the TOOLS_NAME once all the environment for forms-flow-ai-web is ready
        run: |
          if [ '${{ github.ref_name }}' == 'dev' ]; then
            echo "For ${{ github.ref_name }} branch"
            echo "TOOLS_NAME=${{secrets.OC_NAMESPACE_NAMEPLATE}}" >> $GITHUB_ENV
            echo "TAG_NAME="dev"" >> $GITHUB_ENV
            echo "BRANCH_NAME="dev"" >> $GITHUB_ENV
            echo "ENV_NAME="dev"" >> $GITHUB_ENV
          elif [ '${{ github.ref_name }}' == 'main' ]; then
            echo "For ${{ github.ref_name }} branch"
            echo "TOOLS_NAME=${{secrets.OC_NAMESPACE_NAMEPLATE}}" >> $GITHUB_ENV
            echo "TAG_NAME="test"" >> $GITHUB_ENV
            echo "BRANCH_NAME="main"" >> $GITHUB_ENV
            echo "ENV_NAME="test"" >> $GITHUB_ENV
          else
            echo "For ${{ github.ref_name }} branch, defaulting to dev values"
            echo "TOOLS_NAME=${{secrets.OC_NAMESPACE_NAMEPLATE}}" >> $GITHUB_ENV
            echo "TAG_NAME="dev"" >> $GITHUB_ENV
            echo "BRANCH_NAME="dev"" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Login Openshift
        shell: bash
        run: |
          oc login --server=${{secrets.OC_SERVER}} --token=${{secrets.OC_TOKEN}}

      - name: Tools project
        shell: bash
        run: |
          oc project ${{ secrets.OC_NAMESPACE_NAMEPLATE }}-tools

      - name: Start Build Openshift
        shell: bash
        run: |
          oc start-build ${{ env.APP_NAME }}-${{ env.TAG_NAME }}-build --wait
